[package]
name = "security"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
aes = "0.8"
ctr = "0.9"
hex = "0.4"
napi-derive = "2"

[dependencies.napi]
version = "2"
default-features = false
features = ["napi9"]

[dependencies.allocator]
path = "../allocator"

[build-dependencies]
napi-build = "2"
